### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GrafNikola** [PsykoDev/fly-forever#3]
Error: [dispatch] [fly-forever] hook: unmapped packet "S_CANT_FLY_ANYMORE"
    at Dispatch.createHook (C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new fly (C:\Users\Nikolay\Desktop\TeraToolbox\mods\fly-forever-master\index.js:45:6)
    at ModuleManager.load (C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Nikolay\Desktop\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\Nikolay\Desktop\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by GrafNikola** [comment]
S_CANT_FLY_ANYMORE = 59431 
RU
